Repository nuxt-modules/device, pull requests merged in 2024-04, with the labels that each got.

#174 fix: import Nuxt composables from `#imports`
  src/runtime/composables/useDevice.ts
  src/runtime/plugin.ts
Labels: bug, 3.x

#187 docs: use new `nuxi module add` command in installation
  README.md
Labels: 3.x, documentation

#188 ci: add reproduire
  .github/reproduire/needs-reproduction.md
  .github/workflows/reproduire-close.yml
  .github/workflows/reproduire.yml
Labels: 3.x, chore

#181 chore: test bundler module resolution
  .nuxtrc
Labels: 3.x, chore

#211 feat: deprecate `refreshOnResize` option
  src/module.ts
  src/types.ts
Labels: enhancement, 3.x
